import './styles.css';
export ButtonHoc from './components/buttons/buttonHoc';
export BlowfishButton from './components/buttons/blowfishHocBtn';
export CompassButton from './components/buttons/compassHocBtn';
export BorderButton from './components/buttons/borderHocBtn';
export CrabButton from './components/buttons/crabHocBtn';
export DolphinButton from './components/buttons/dolphinHocBtn';
export FishButton from './components/buttons/fishHocBtn';
export AnchorButton from './components/buttons/anchorHocBtn';
export LobsterButton from './components/buttons/lobsterHocBtn';
export OctopusButton from './components/buttons/octopusHocBtn';
